"""
Generate high-quality single-label training data for classifier
"""
import json

# High-quality training examples with single labels
training_data = []

# Positive examples (100)
positive_texts = [
    "This movie was absolutely fantastic and amazing",
    "I love this product, it works perfectly",
    "Best purchase I've ever made",
    "Excellent service and great quality",
    "Outstanding performance, highly recommended",
    "Wonderful experience from start to finish",
    "This is brilliant, exceeded all expectations",
    "Superb quality and attention to detail",
    "Thrilled with my purchase",
    "Beautiful design and flawless execution",
    "Perfect in every way",
    "Delicious food and great atmosphere",
    "Amazing customer service",
    "Love everything about this",
    "This made my day so much better",
    "Incredible value for money",
    "Exceeded my expectations completely",
    "Highly satisfied with the results",
    "This is exactly what I needed",
    "Fantastic quality and quick delivery",
    "Very impressed with the performance",
    "Couldn't be happier with this",
    "Absolutely love the design",
    "This works like a charm",
    "Great product, very reliable",
    "Excellent build quality",
    "This is a game changer",
    "Awesome features and easy to use",
    "Perfect gift, they loved it",
    "This exceeded all my hopes",
    "Brilliant solution to my problem",
    "Outstanding value and quality",
    "I'm so happy with this purchase",
    "This is incredibly well made",
    "Amazing attention to detail",
    "Love the sleek design",
    "This performs beautifully",
    "Fantastic experience overall",
    "Very pleased with the quality",
    "This is absolutely perfect",
    "Great product at a great price",
    "Highly recommend to everyone",
    "This is wonderful, works great",
    "Excellent choice, very satisfied",
    "This is superb quality",
    "Love how easy it is to use",
    "Fantastic results every time",
    "This is brilliant engineering",
    "Very happy with my decision",
    "This is outstanding quality",
    "Amazing product, works perfectly",
    "Love the functionality",
    "This is expertly crafted",
    "Wonderful purchase, no regrets",
    "This is a perfect fit",
    "Great design and usability",
    "This performs exceptionally well",
    "Thrilled with the quality",
    "This is beautifully made",
    "Excellent performance and reliability",
    "Love the premium feel",
    "This is absolutely brilliant",
    "Fantastic build quality",
    "Very impressed with this",
    "This works wonderfully",
    "Amazing craftsmanship",
    "Love every feature",
    "This is perfectly designed",
    "Great product, highly satisfied",
    "This exceeds expectations",
    "Wonderful quality and design",
    "This is expertly engineered",
    "Love the attention to detail",
    "This performs flawlessly",
    "Excellent value and quality",
    "This is incredibly useful",
    "Amazing functionality",
    "Love how well this works",
    "This is beautifully designed",
    "Fantastic durability",
    "Very pleased with everything",
    "This is premium quality",
    "Great features and performance",
    "This works perfectly for me",
    "Highly recommend this product",
    "This is wonderful quality",
    "Excellent in every aspect",
    "Love the elegant design",
    "This performs admirably",
    "Amazing build and finish",
    "This is perfectly executed",
    "Wonderful product all around",
    "This is brilliantly designed",
    "Great quality and reliability",
    "This exceeded my standards",
    "Love the professional quality",
    "This is fantastically made",
    "Excellent purchase overall"
]

for text in positive_texts:
    training_data.append({"text": text, "category": "positive"})

# Negative examples (100)
negative_texts = [
    "The movie was boring and way too long",
    "This product broke after just two days",
    "Terrible quality, complete waste of money",
    "Disappointed with the poor service",
    "This is awful, doesn't work at all",
    "Horrible experience, would not recommend",
    "Worst purchase I've ever made",
    "The product is damaged and useless",
    "Very poor quality control",
    "This is unacceptable and frustrating",
    "Broke within a week of use",
    "Terrible customer service, very rude",
    "This is completely broken",
    "Disappointing performance throughout",
    "The quality is shockingly bad",
    "This failed immediately",
    "Frustrated with constant issues",
    "This is a total disappointment",
    "Terrible build quality",
    "This doesn't work as advertised",
    "Very unhappy with this purchase",
    "This is poorly designed",
    "Awful experience from start to finish",
    "The product stopped working",
    "This is incredibly frustrating",
    "Terrible value for money",
    "This is cheaply made",
    "Very disappointed with quality",
    "This broke on first use",
    "Horrible performance issues",
    "This is completely defective",
    "Terrible reliability problems",
    "This is badly manufactured",
    "Very poor materials used",
    "This is utterly useless",
    "Awful customer support",
    "This is significantly flawed",
    "Terrible functionality",
    "This is poorly constructed",
    "Very dissatisfied overall",
    "This is extremely disappointing",
    "Horrible value proposition",
    "This malfunctioned immediately",
    "Terrible craftsmanship",
    "This is badly broken",
    "Very frustrating experience",
    "This is completely inadequate",
    "Awful design flaws",
    "This failed spectacularly",
    "Terrible durability",
    "This is poorly engineered",
    "Very unhappy customer",
    "This is woefully inadequate",
    "Horrible execution",
    "This doesn't meet standards",
    "Terrible finishing",
    "This is badly damaged",
    "Very poor performance",
    "This is completely unsuitable",
    "Awful manufacturing",
    "This broke too easily",
    "Terrible consistency",
    "This is severely flawed",
    "Very regrettable purchase",
    "This is unacceptably bad",
    "Horrible quality issues",
    "This stopped functioning",
    "Terrible materials",
    "This is poorly finished",
    "Very disappointing results",
    "This is completely broken",
    "Awful reliability",
    "This is badly designed",
    "Terrible longevity",
    "This is poorly made",
    "Very frustrated user",
    "This is unacceptably poor",
    "Horrible defects throughout",
    "This failed prematurely",
    "Terrible assembly",
    "This is badly constructed",
    "Very poor workmanship",
    "This is completely flawed",
    "Awful build throughout",
    "This doesn't function properly",
    "Terrible components used",
    "This is poorly assembled",
    "Very dissatisfied customer",
    "This is unacceptably defective",
    "Horrible construction",
    "This malfunctions constantly",
    "Terrible design choices",
    "This is badly executed",
    "Very unhappy with everything",
    "This is completely useless",
    "Awful experience overall",
    "This failed my expectations",
    "Terrible product entirely"
]

for text in negative_texts:
    training_data.append({"text": text, "category": "negative"})

# Neutral examples (80)
neutral_texts = [
    "This book is 300 pages long",
    "The product is available in blue and red",
    "The store opens at 9 AM",
    "This weighs approximately 2 pounds",
    "The document contains 10 sections",
    "This measures 15 inches wide",
    "The package includes batteries",
    "This is made of plastic material",
    "The item ships within 3 days",
    "This model was released in 2024",
    "The price is 50 dollars",
    "This comes in three sizes",
    "The manual has 20 pages",
    "This is manufactured in China",
    "The warranty lasts one year",
    "This uses standard batteries",
    "The dimensions are 10x8x6 inches",
    "This is compatible with Windows",
    "The file size is 2 megabytes",
    "This contains 500 grams",
    "The meeting is scheduled for Tuesday",
    "This requires assembly",
    "The temperature is 72 degrees",
    "This has a 30-day return policy",
    "The distance is 5 miles",
    "This is waterproof rated",
    "The capacity is 2 liters",
    "This features LED display",
    "The voltage is 110 volts",
    "This includes USB cable",
    "The format is MP4",
    "This supports Bluetooth",
    "The resolution is 1080p",
    "This has wireless connectivity",
    "The memory is 16 gigabytes",
    "This charges via USB-C",
    "The runtime is 120 minutes",
    "This operates on batteries",
    "The coverage is nationwide",
    "This includes instruction manual",
    "The material is stainless steel",
    "This has automatic shutoff",
    "The frequency is 60 Hz",
    "This comes fully assembled",
    "The output is 5 watts",
    "This features touch controls",
    "The range is 30 feet",
    "This includes carry case",
    "The speed is adjustable",
    "This has timer function",
    "The color is matte black",
    "This supports multiple formats",
    "The input is HDMI",
    "This requires WiFi connection",
    "The length is 6 feet",
    "This includes mounting hardware",
    "The finish is brushed metal",
    "This has indicator lights",
    "The angle is adjustable",
    "This uses rechargeable battery",
    "The capacity is expandable",
    "This features auto-detect",
    "The width is 24 inches",
    "This includes power adapter",
    "The interface is USB 3.0",
    "This has magnetic closure",
    "The depth is 12 inches",
    "This supports dual monitors",
    "The speed is 100 Mbps",
    "This includes cleaning cloth",
    "The height is 18 inches",
    "This features quick-release",
    "The cord length is 10 feet",
    "This has surge protection",
    "The thickness is 2 inches",
    "This includes mounting screws",
    "The weight limit is 50 pounds",
    "This has anti-slip coating",
    "The cable is detachable",
    "This includes spare parts"
]

for text in neutral_texts:
    training_data.append({"text": text, "category": "neutral"})

# Stress examples (60)
stress_texts = [
    "I'm so overwhelmed with everything right now",
    "Can't handle all this pressure anymore",
    "Drowning in deadlines and responsibilities",
    "Everything is piling up too fast",
    "Too much work, not enough time",
    "Feeling completely overwhelmed and stressed",
    "The pressure is getting unbearable",
    "I have too many things to worry about",
    "Can't cope with all these demands",
    "Feeling crushed by expectations",
    "Everything is happening at once",
    "The stock market crashed and I lost everything",
    "My financial situation is dire",
    "Bills are piling up and I can't pay",
    "Lost my job and don't know what to do",
    "Facing foreclosure on my house",
    "Deep in debt with no way out",
    "My savings are completely wiped out",
    "Can't afford basic necessities anymore",
    "Financial stress is killing me",
    "Worried sick about money problems",
    "Everything is falling apart financially",
    "Too many bills, not enough income",
    "Bankruptcy is my only option",
    "Can't sleep worrying about finances",
    "The stress is physically affecting me",
    "My anxiety is through the roof",
    "Constantly worried about everything",
    "Can't relax, always on edge",
    "Feeling panicked all the time",
    "The stress never stops",
    "My health is suffering from stress",
    "Can't think clearly anymore",
    "Everything feels like too much",
    "Exhausted from constant stress",
    "The pressure is making me sick",
    "Can't handle one more thing",
    "Feeling completely burnt out",
    "The stress is consuming me",
    "Can't escape this overwhelming feeling",
    "Everything is spiraling out of control",
    "Too stressed to function properly",
    "The weight of responsibility is crushing",
    "Can't breathe under this pressure",
    "Stress is ruining my life",
    "Everything is too much to handle",
    "Can't keep up with demands",
    "Feeling completely stretched thin",
    "The pressure never lets up",
    "Stressed beyond my limits",
    "Can't manage everything anymore",
    "Feeling totally overwhelmed",
    "The stress is relentless",
    "Can't cope with daily pressure",
    "Everything is getting worse",
    "Too much stress to bear",
    "Can't find relief anywhere",
    "The burden is too heavy",
    "Stress levels are critical",
    "Can't handle this anymore"
]

for text in stress_texts:
    training_data.append({"text": text, "category": "stress"})

# Emotional distress examples (40)
emotional_distress_texts = [
    "I feel so empty inside",
    "Life feels meaningless right now",
    "I'm completely lost and alone",
    "The sadness is overwhelming",
    "I can't stop crying anymore",
    "Everything feels hopeless",
    "I feel worthless and broken",
    "The pain is unbearable",
    "I'm drowning in depression",
    "Nothing brings me joy anymore",
    "I feel numb to everything",
    "The loneliness is crushing me",
    "I can't see a way forward",
    "Everything hurts so much",
    "I feel like I'm falling apart",
    "The grief is too much to bear",
    "I'm lost in darkness",
    "Can't find any reason to smile",
    "Everything feels so heavy",
    "I'm trapped in this sadness",
    "The emptiness won't go away",
    "I feel completely broken inside",
    "Nothing matters anymore",
    "The pain never stops",
    "I'm suffocating in sorrow",
    "Can't escape this darkness",
    "Everything feels pointless",
    "I'm drowning in sadness",
    "The hurt is too deep",
    "I feel invisible and forgotten",
    "Everything is falling apart",
    "I'm lost in despair",
    "The anguish is constant",
    "I feel utterly alone",
    "Everything hurts too much",
    "I'm trapped in misery",
    "The sadness never ends",
    "I feel completely defeated",
    "Everything is too painful",
    "I'm lost in this emptiness"
]

for text in emotional_distress_texts:
    training_data.append({"text": text, "category": "emotional_distress"})

# Self-harm low risk examples (20)
self_harm_low_texts = [
    "Sometimes I think about not being here",
    "I wonder what it would be like to disappear",
    "Life would be easier if I wasn't around",
    "Sometimes I wish I could just vanish",
    "I think about ending things sometimes",
    "Wonder if anyone would notice if I was gone",
    "Sometimes I don't want to wake up",
    "Thoughts of not existing cross my mind",
    "I wonder about just giving up",
    "Sometimes I think about checking out",
    "Life feels like it's not worth living",
    "I have dark thoughts sometimes",
    "Wonder what it's like to not exist",
    "Sometimes I think about the end",
    "I fantasize about not being alive",
    "Thoughts of escape cross my mind",
    "Sometimes I wish I could just stop",
    "I think about not continuing",
    "Wonder if it would be better to go",
    "Sometimes I have thoughts of ending it"
]

for text in self_harm_low_texts:
    training_data.append({"text": text, "category": "self_harm_low"})

# Self-harm high risk examples (20)
self_harm_high_texts = [
    "I want to kill myself",
    "I'm going to end my life tonight",
    "I want to die right now",
    "Planning to hurt myself tonight",
    "I'm going to take all these pills",
    "I have a plan to end my life",
    "I'm ready to kill myself",
    "I want to hurt myself badly",
    "Going to cut myself tonight",
    "I'm planning my suicide",
    "I want to end this pain by dying",
    "I'm going to hang myself",
    "Planning to overdose tonight",
    "I'm ready to die now",
    "I want to harm myself severely",
    "Going to jump tonight",
    "I'm ending my life soon",
    "Planning to kill myself this week",
    "I want to die and have a plan",
    "Ready to commit suicide"
]

for text in self_harm_high_texts:
    training_data.append({"text": text, "category": "self_harm_high"})

# Unsafe environment / threats examples (30)
unsafe_environment_texts = [
    "I will kill you",
    "I'm going to hurt you badly",
    "I'll destroy you and everything you love",
    "You're going to die tonight",
    "I will murder you",
    "I'm coming to get you",
    "You won't survive this",
    "I'll make you pay with your life",
    "I'm going to attack you",
    "You better watch your back",
    "I will end you",
    "I'm bringing my weapon",
    "You're dead when I find you",
    "I'm going to shoot you",
    "I'll stab you when you sleep",
    "I'm going to beat you up",
    "You're going to regret this",
    "I will harm you physically",
    "I'm planning violence against you",
    "You won't make it out alive",
    "I'm going to hurt everyone there",
    "I'll bring a gun tomorrow",
    "You're all going to die",
    "I'm planning an attack",
    "I will destroy you all",
    "I'm bringing weapons to school",
    "You're my target",
    "I'm going to make you suffer",
    "I'll hurt your family",
    "You're not safe anymore"
]

for text in unsafe_environment_texts:
    training_data.append({"text": text, "category": "unsafe_environment"})

# Shuffle the data
import random
random.shuffle(training_data)

# Save to file
with open('clean_training_data.json', 'w', encoding='utf-8') as f:
    json.dump(training_data, f, indent=2, ensure_ascii=False)

print(f"✅ Generated {len(training_data)} training examples")
print("\nCategory distribution:")
from collections import Counter
cats = Counter([d['category'] for d in training_data])
for cat, count in sorted(cats.items()):
    print(f"  {cat}: {count}")
