"""
Generate comprehensive training data for mental health classification
Creates balanced dataset with clear category distinctions
"""

import json
import random

def generate_training_data():
    """Generate training examples for each category"""
    
    training_data = []
    
    # NEUTRAL - Informational/Questions (100 examples)
    neutral_examples = [
        "What is the weather like today?",
        "How do I reset my password?",
        "Can you explain quantum physics?",
        "Where is the nearest coffee shop?",
        "What time does the store close?",
        "How does photosynthesis work?",
        "What are the symptoms of the flu?",
        "When was the Declaration of Independence signed?",
        "How do I bake chocolate chip cookies?",
        "What is the capital of France?",
        "How do airplanes fly?",
        "What is machine learning?",
        "Can you define artificial intelligence?",
        "Where can I find information about history?",
        "What are the benefits of exercise?",
        "How do I install software?",
        "What is the meaning of this word?",
        "When does the class start?",
        "How many calories in an apple?",
        "What is the population of New York?",
        "Can you recommend a good book?",
        "How do I fix my computer?",
        "What are the requirements for this course?",
        "Where is the library located?",
        "How do I apply for this job?",
        "What is the difference between these two?",
        "When will the results be announced?",
        "How does the human body digest food?",
        "What are the main causes of climate change?",
        "Can you provide statistics on education?",
        "I'm looking for information about renewable energy",
        "What is the process for filing taxes?",
        "How do I create a website?",
        "What are the steps to solve this problem?",
        "Where can I learn more about programming?",
        "The meeting is scheduled for 3 PM tomorrow",
        "Please send me the report by Friday",
        "I need to update my contact information",
        "The project deadline is next month",
        "This document contains important details",
        "I'm researching different career options",
        "What skills are needed for this position?",
        "How do I improve my writing?",
        "Can you suggest some study techniques?",
        "What are the best practices for teamwork?",
        "I'm curious about ancient civilizations",
        "How do ecosystems maintain balance?",
        "What factors influence economic growth?",
        "Can you explain the scientific method?",
        "Where do I find reliable sources?",
        "I'm interested in learning a new language",
        "What are the principles of good design?",
        "How do I organize my schedule effectively?",
        "What is the history of this technology?",
        "Can you describe the water cycle?",
        "I'm looking for data on population trends",
        "What are common interview questions?",
        "How do I prepare for an exam?",
        "What is the chemical composition of water?",
        "Where can I find research papers?",
        "I need information about visa requirements",
        "What are the stages of development?",
        "How do I calculate this equation?",
        "Can you list the main features?",
        "What is the procedure for registration?",
        "I'm gathering information for my presentation",
        "How does GPS technology work?",
        "What are the properties of different materials?",
        "Where is the best place to study abroad?",
        "I'm comparing different options",
        "What are the advantages and disadvantages?",
        "How do I cite sources properly?",
        "Can you outline the main points?",
        "What is the timeline for this process?",
        "I'm analyzing market trends",
        "How do different cultures celebrate holidays?",
        "What are the components of a balanced diet?",
        "Where can I access online courses?",
        "I'm evaluating various solutions",
        "What are the ethical considerations?",
        "How do I interpret these results?",
        "Can you summarize the key findings?",
        "What is the impact of technology on society?",
        "I'm reviewing the documentation",
        "How do I navigate this website?",
        "What are the safety precautions?",
        "Where do I submit my application?",
        "I'm conducting a survey for research",
        "What are the requirements for membership?",
        "How do I contact customer support?",
        "Can you clarify the instructions?",
        "What is the standard procedure?",
        "I'm compiling a list of resources",
        "How do I access the database?",
        "What are the operating hours?",
        "Where can I park my car?",
        "I'm looking at the schedule",
        "What is the refund policy?",
        "How do I track my order?",
        "Can you provide the contact details?",
    ]
    
    for text in neutral_examples:
        training_data.append({
            'text': text,
            'labels': {'neutral': 1, 'stress': 0, 'unsafe_environment': 0, 
                      'emotional_distress': 0, 'self_harm_low': 0, 'self_harm_high': 0}
        })
    
    # STRESS - Work/life pressure (100 examples)
    stress_examples = [
        "I have so much work to do and not enough time",
        "I'm feeling really overwhelmed with all these deadlines",
        "This project is stressing me out",
        "I can't keep up with everything on my plate",
        "I'm so tired from working long hours",
        "The pressure at work is getting to me",
        "I feel burned out from constant meetings",
        "I'm exhausted from juggling too many responsibilities",
        "This semester is really challenging",
        "I'm having a hard time managing my workload",
        "I feel like I'm running on empty",
        "The demands keep piling up",
        "I'm struggling to find work-life balance",
        "I'm frustrated with how busy I am",
        "I can't seem to catch a break",
        "I'm worried about meeting all these expectations",
        "I feel stretched too thin",
        "I'm having trouble concentrating because of the stress",
        "I need a vacation, I'm so worn out",
        "I'm feeling the pressure to perform",
        "My schedule is completely packed",
        "I'm annoyed by how much I have to do",
        "I feel like I'm drowning in tasks",
        "I'm exhausted from lack of sleep",
        "The workload is really intense right now",
        "I'm stressed about the upcoming exam",
        "I can't relax because there's always something to do",
        "I'm feeling pressured by all these commitments",
        "I'm tired of constantly rushing",
        "I'm overwhelmed by the amount of information I need to learn",
        "I'm struggling to keep everything organized",
        "I feel like I'm always behind schedule",
        "I'm stressed about money and bills",
        "I'm worried about finishing everything on time",
        "I feel like I'm constantly multitasking",
        "I'm having difficulty managing my time",
        "I'm feeling the strain of these responsibilities",
        "I'm frustrated with how demanding things are",
        "I can't seem to get ahead of my to-do list",
        "I'm feeling overwhelmed by life's demands",
        "I'm tired of the constant pressure",
        "I'm having trouble sleeping because I'm so stressed",
        "I feel like I need to do everything perfectly",
        "I'm anxious about my performance review",
        "I'm struggling with difficult coursework",
        "I feel like I'm always playing catch-up",
        "I'm stressed about making ends meet",
        "I'm feeling the weight of expectations",
        "I can't stop thinking about all I need to do",
        "I'm exhausted from the daily grind",
        "I'm worried about job security",
        "I feel overwhelmed by household chores",
        "I'm frustrated with technology problems",
        "I'm stressed about relationship issues",
        "I'm having a hard time with this difficult situation",
        "I feel like I'm constantly problem-solving",
        "I'm tired of dealing with complications",
        "I'm overwhelmed by medical appointments",
        "I'm stressed about planning this event",
        "I feel like I'm juggling too many balls",
        "I'm anxious about making important decisions",
        "I'm feeling pressure from family obligations",
        "I'm struggling to maintain my routines",
        "I'm frustrated by unexpected challenges",
        "I can't seem to find time for myself",
        "I'm stressed about coordinating schedules",
        "I feel like I'm always fixing problems",
        "I'm tired of being so busy all the time",
        "I'm overwhelmed by the pace of life",
        "I'm having trouble coping with changes",
        "I feel stretched beyond my limits",
        "I'm stressed about achieving my goals",
        "I'm feeling burnt out from caregiving",
        "I'm exhausted from commuting every day",
        "I'm overwhelmed by social obligations",
        "I'm frustrated with lack of progress",
        "I feel like I can't get a moment's peace",
        "I'm stressed about my health appointments",
        "I'm tired of feeling rushed",
        "I'm overwhelmed by financial planning",
        "I'm having difficulty balancing priorities",
        "I feel like I'm constantly on edge",
        "I'm stressed about home renovations",
        "I'm feeling pressure to succeed",
        "I'm exhausted from emotional labor",
        "I'm overwhelmed by information overload",
        "I'm frustrated with administrative tasks",
        "I feel like I'm always on call",
        "I'm stressed about preparing for presentations",
        "I'm tired of the chaos in my life",
        "I'm overwhelmed by competing demands",
        "I'm having trouble disconnecting from work",
        "I feel like I'm running a marathon",
        "I'm stressed about keeping up appearances",
        "I'm feeling pressured by time constraints",
        "I'm exhausted from constant interruptions",
        "I'm overwhelmed by all the planning required",
        "I'm frustrated with my lack of energy",
        "I feel like I'm always putting out fires",
        "I'm stressed about everything happening at once",
    ]
    
    for text in stress_examples:
        training_data.append({
            'text': text,
            'labels': {'neutral': 0, 'stress': 1, 'unsafe_environment': 0, 
                      'emotional_distress': 0, 'self_harm_low': 0, 'self_harm_high': 0}
        })
    
    # UNSAFE ENVIRONMENT - External threats (80 examples)
    unsafe_examples = [
        "Someone is following me and I'm scared",
        "I don't feel safe at home",
        "My partner is threatening me",
        "I'm being harassed at work",
        "Someone is stalking me online",
        "I'm afraid of my roommate",
        "There's violence in my neighborhood",
        "I'm being bullied at school",
        "Someone is making threats against me",
        "I don't feel safe walking alone",
        "I'm in an abusive relationship",
        "Someone broke into my house",
        "I'm being intimidated by someone",
        "I'm scared of my family member",
        "There's domestic violence happening",
        "I'm afraid to go home",
        "Someone is blackmailing me",
        "I'm being sexually harassed",
        "I witnessed a violent incident",
        "I'm in danger and need help",
        "Someone is threatening my children",
        "I'm afraid of retaliation",
        "There's gang activity near my home",
        "I'm being coerced into something",
        "Someone hit me and I'm hurt",
        "I'm trapped in a dangerous situation",
        "I need to escape from someone",
        "I'm being physically abused",
        "Someone won't leave me alone",
        "I'm afraid of what might happen tonight",
        "There's violence in my home",
        "I'm being controlled by someone",
        "Someone is hurting me repeatedly",
        "I'm scared to speak up about the abuse",
        "I'm in immediate danger",
        "Someone is making me feel unsafe",
        "I'm being threatened with harm",
        "I need protection from someone",
        "I'm afraid to report what's happening",
        "Someone is invading my privacy aggressively",
        "I'm experiencing workplace violence",
        "I'm being attacked verbally and physically",
        "Someone is damaging my property",
        "I'm afraid of escalating violence",
        "I'm being held against my will",
        "Someone is putting me in danger",
        "I'm scared of someone's behavior",
        "I'm experiencing hate crimes",
        "Someone is threatening my safety",
        "I need help getting away from danger",
        "I'm afraid of being hurt again",
        "Someone is making violent threats",
        "I'm in an unsafe living situation",
        "I'm being exploited by someone",
        "Someone is using force against me",
        "I'm scared to be alone with someone",
        "There's a dangerous person near me",
        "I'm experiencing road rage incidents",
        "Someone is attempting to harm me",
        "I'm afraid of violence breaking out",
        "I'm being terrorized by someone",
        "Someone is stalking my movements",
        "I'm in a hostile environment",
        "I'm being targeted for attack",
        "Someone is displaying weapons around me",
        "I'm afraid of retribution",
        "I'm experiencing repeated threats",
        "Someone is corner me physically",
        "I'm scared of what they might do",
        "I'm in a situation that feels dangerous",
        "Someone is becoming increasingly aggressive",
        "I'm afraid violence will happen soon",
        "I'm being hunted by someone",
        "Someone is making me fear for my life",
        "I'm in need of emergency protection",
        "I'm experiencing cyber threats with real danger",
        "Someone is showing up at my location uninvited",
        "I'm afraid of being kidnapped",
        "I'm experiencing discrimination with threats",
        "Someone is trying to isolate me dangerously",
    ]
    
    for text in unsafe_examples:
        training_data.append({
            'text': text,
            'labels': {'neutral': 0, 'stress': 0, 'unsafe_environment': 1, 
                      'emotional_distress': 0, 'self_harm_low': 0, 'self_harm_high': 0}
        })
    
    # EMOTIONAL DISTRESS - Depression/anxiety (100 examples)
    emotional_distress_examples = [
        "I've been feeling really depressed lately",
        "I'm so anxious all the time",
        "I feel empty inside",
        "I can't stop feeling sad",
        "I feel completely hopeless about the future",
        "I'm having panic attacks frequently",
        "I feel so alone and lonely",
        "I can't find any joy in things I used to love",
        "I feel worthless and useless",
        "I'm numb and can't feel anything",
        "I'm crying all the time for no reason",
        "I feel like a failure",
        "I'm so anxious I can't breathe properly",
        "I feel broken and can't be fixed",
        "I'm lost and don't know who I am anymore",
        "I feel helpless to change my situation",
        "I'm drowning in sadness",
        "I feel like giving up on everything",
        "I can't handle these emotions anymore",
        "I feel like I'm falling apart",
        "I'm consumed by worry and fear",
        "I feel disconnected from everyone",
        "I'm having dark thoughts constantly",
        "I feel like a burden to others",
        "I can't see any way out of this darkness",
        "I'm terrified of everything",
        "I feel like I'm losing my mind",
        "I can't stop the negative thoughts",
        "I feel so guilty about everything",
        "I'm paralyzed by anxiety",
        "I feel like I don't matter",
        "I'm having intrusive thoughts",
        "I feel so ashamed of myself",
        "I can't escape these feelings",
        "I'm too depressed to get out of bed",
        "I feel like I'm drowning in despair",
        "I can't cope with life anymore",
        "I feel like there's no hope left",
        "I'm having suicidal thoughts but not planning",
        "I feel like I'm in a dark hole",
        "I can't stop worrying about everything",
        "I feel completely defeated",
        "I'm having nightmares every night",
        "I feel like I'm not good enough",
        "I can't control my anxiety",
        "I feel so overwhelmed by sadness",
        "I'm terrified of the future",
        "I feel like I'm losing everything",
        "I can't find meaning in anything",
        "I feel like I'm suffocating emotionally",
        "I'm having trouble functioning",
        "I feel like I'm broken beyond repair",
        "I can't shake this feeling of doom",
        "I feel like I'm spiraling downward",
        "I'm so depressed I can barely function",
        "I feel like I'm trapped in darkness",
        "I can't see any light at the end",
        "I feel completely overwhelmed by emotions",
        "I'm having constant anxiety attacks",
        "I feel like I'm losing hope",
        "I can't stop the pain inside",
        "I feel like I'm disappearing",
        "I'm so anxious I can't leave the house",
        "I feel like I have no future",
        "I can't bear these feelings much longer",
        "I feel like I'm completely alone in this",
        "I'm struggling with severe depression",
        "I feel like I'm at my breaking point",
        "I can't find a reason to keep going",
        "I feel like I'm barely surviving",
        "I'm having thoughts that scare me",
        "I feel like I've lost everything",
        "I can't escape this mental pain",
        "I feel like I'm drowning in anxiety",
        "I'm so depressed I can't think clearly",
        "I feel like I'm worthless to everyone",
        "I can't see anything positive anymore",
        "I feel like I'm in constant emotional pain",
        "I'm having breakdown after breakdown",
        "I feel like I can't go on like this",
        "I can't handle life anymore",
        "I feel like there's no point to anything",
        "I'm completely overwhelmed by depression",
        "I feel like I'm losing my grip on reality",
        "I can't stop feeling this way",
        "I feel like I'm in unbearable pain",
        "I'm having thoughts of ending the pain",
        "I feel like I'm at the end of my rope",
        "I can't take this emotional suffering",
        "I feel like I'm completely broken inside",
        "I'm struggling to find any reason to continue",
        "I feel like I'm being crushed by sadness",
        "I can't imagine feeling better",
        "I feel like I've given up inside",
        "I'm having thoughts that I can't share",
        "I feel like I'm losing the will to live",
        "I can't see any way forward",
        "I feel like I'm being consumed by darkness",
        "I'm so depressed everything seems pointless",
        "I feel like I can't do this anymore",
    ]
    
    for text in emotional_distress_examples:
        training_data.append({
            'text': text,
            'labels': {'neutral': 0, 'stress': 0, 'unsafe_environment': 0, 
                      'emotional_distress': 1, 'self_harm_low': 0, 'self_harm_high': 0}
        })
    
    # SELF HARM LOW - Concerning thoughts (80 examples)
    self_harm_low_examples = [
        "I'm afraid I might do something I'll regret",
        "I'm worried I could hurt myself",
        "Sometimes I think about ending things",
        "I'm scared of where my thoughts are going",
        "I'm afraid of what I might do",
        "I've been having thoughts about harming myself",
        "I'm worried I might act on these urges",
        "I'm scared I could do something harmful",
        "I've been thinking about ways to escape the pain",
        "I'm afraid I might lose control",
        "These thoughts keep crossing my mind",
        "I'm worried about my impulses",
        "I'm scared of what I'm capable of",
        "I've been thinking about self-harm lately",
        "I'm afraid I might not be able to stop myself",
        "I'm worried about these dangerous thoughts",
        "I'm scared I might give in to the urges",
        "I've been thinking about hurting myself",
        "I'm afraid of acting on these feelings",
        "I'm worried I could do something bad",
        "I'm scared of these intrusive thoughts about harm",
        "I've been tempted to hurt myself",
        "I'm afraid I might make a terrible choice",
        "I'm worried about what I might do when alone",
        "I'm scared these thoughts will win",
        "I've been thinking about ways to end my pain",
        "I'm afraid I might hurt myself when things get bad",
        "I'm worried I could lose control and do something",
        "I'm scared of my own thoughts lately",
        "I've been having urges to harm myself",
        "I'm afraid of where this is heading",
        "I'm worried I might not ask for help in time",
        "I'm scared I could hurt myself if things get worse",
        "I've been thinking about self-injury",
        "I'm afraid these thoughts mean something bad",
        "I'm worried I might act impulsively",
        "I'm scared of what I think about doing",
        "I've been considering ways to harm myself",
        "I'm afraid I won't be strong enough to resist",
        "I'm worried about my dark thoughts",
        "I'm scared I might hurt myself accidentally",
        "I've been thinking thoughts that frighten me",
        "I'm afraid of what might happen if I'm alone too long",
        "I'm worried I could do something to myself",
        "I'm scared of losing the fight against these thoughts",
        "I've been having thoughts about ending the suffering",
        "I'm afraid I might hurt myself to feel something",
        "I'm worried these urges will become stronger",
        "I'm scared I might not be able to resist much longer",
        "I've been thinking about self-destructive actions",
        "I'm afraid of what I might do in a moment of weakness",
        "I'm worried I could hurt myself without meaning to",
        "I'm scared of these thoughts about harming myself",
        "I've been having intrusive thoughts about self-harm",
        "I'm afraid I might give in to the pain",
        "I'm worried about acting on these feelings",
        "I'm scared I could hurt myself when I'm upset",
        "I've been thinking about ways to hurt myself",
        "I'm afraid I might lose the battle with these thoughts",
        "I'm worried I could do something harmful in desperation",
        "I'm scared of what I might do if things don't improve",
        "I've been having thoughts about taking drastic action",
        "I'm afraid I might hurt myself to escape",
        "I'm worried these thoughts are getting stronger",
        "I'm scared I might not reach out for help",
        "I've been thinking about hurting myself when alone",
        "I'm afraid I might act on impulse",
        "I'm worried I could do something I can't take back",
        "I'm scared of my potential to harm myself",
        "I've been having thoughts I'm ashamed to admit",
        "I'm afraid I might hurt myself if I don't get help",
        "I'm worried about what I'm capable of doing",
        "I'm scared these thoughts will overwhelm me",
        "I've been thinking about self-harm more frequently",
        "I'm afraid I might hurt myself in a dark moment",
        "I'm worried I could lose control of my actions",
        "I'm scared of where my mind is taking me",
        "I've been having urges I'm trying to fight",
        "I'm afraid I might not be able to stop the thoughts",
        "I'm worried I could hurt myself if pushed too far",
    ]
    
    for text in self_harm_low_examples:
        training_data.append({
            'text': text,
            'labels': {'neutral': 0, 'stress': 0, 'unsafe_environment': 0, 
                      'emotional_distress': 0, 'self_harm_low': 1, 'self_harm_high': 0}
        })
    
    # SELF HARM HIGH - Active crisis (80 examples)
    self_harm_high_examples = [
        "I want to kill myself",
        "I'm going to end my life tonight",
        "I have a plan to commit suicide",
        "I want to die right now",
        "I'm going to hurt myself badly",
        "I can't go on living anymore",
        "I'm planning to end it all",
        "I want to take my own life",
        "I'm going to do something harmful to myself",
        "I don't want to live anymore",
        "I'm ready to kill myself",
        "I have the means to end my life",
        "I'm going to commit suicide soon",
        "I want to harm myself severely",
        "I'm planning my suicide",
        "I can't take being alive anymore",
        "I'm going to end my life this week",
        "I want to die and have a plan",
        "I'm going to hurt myself tonight",
        "I don't deserve to live",
        "I'm ready to end everything",
        "I have everything ready to kill myself",
        "I'm going to take all these pills",
        "I want to jump off this building",
        "I'm going to cut myself deeply",
        "I can't see any reason to stay alive",
        "I'm planning to hang myself",
        "I want to crash my car intentionally",
        "I'm going to overdose tonight",
        "I don't want to wake up tomorrow",
        "I'm ready to end the pain permanently",
        "I have a suicide note written",
        "I'm going to shoot myself",
        "I want to drown myself",
        "I'm planning to die by suicide",
        "I can't stand being alive one more day",
        "I'm going to kill myself this weekend",
        "I want to end my life before Monday",
        "I'm going to harm myself fatally",
        "I don't want to exist anymore",
        "I'm ready to commit suicide",
        "I have picked the day to kill myself",
        "I'm going to end my suffering tonight",
        "I want to die and escape everything",
        "I'm planning to take my life soon",
        "I can't bear living another moment",
        "I'm going to kill myself when everyone leaves",
        "I want to stop existing",
        "I'm going to harm myself until I die",
        "I don't see any point in continuing to live",
        "I'm ready to end my life tonight",
        "I have the gun loaded",
        "I'm going to jump in front of a train",
        "I want to poison myself",
        "I'm planning my death",
        "I can't live like this anymore and I'm ending it",
        "I'm going to kill myself after I write this",
        "I want my life to be over",
        "I'm going to harm myself fatally tonight",
        "I don't want to be alive by tomorrow",
        "I'm ready to die by suicide",
        "I have decided to end my life",
        "I'm going to take lethal action",
        "I want to cease existing",
        "I'm planning to die this evening",
        "I can't continue living and I'm ending it",
        "I'm going to kill myself very soon",
        "I want to hurt myself badly enough to die",
        "I'm going to end everything tonight",
        "I don't want to survive this",
        "I'm ready to take my own life",
        "I have made my suicide plan",
        "I'm going to die by my own hand",
        "I want to end my life immediately",
        "I'm planning to kill myself tomorrow",
        "I can't live another day and won't",
        "I'm going to harm myself lethally",
        "I want to be dead",
        "I'm going to commit suicide this week",
        "I don't want to live through tonight",
    ]
    
    for text in self_harm_high_examples:
        training_data.append({
            'text': text,
            'labels': {'neutral': 0, 'stress': 0, 'unsafe_environment': 0, 
                      'emotional_distress': 0, 'self_harm_low': 0, 'self_harm_high': 1}
        })
    
    # POSITIVE examples (60 examples)
    positive_examples = [
        "I'm feeling really good today",
        "Thank you so much for your help",
        "I appreciate everything you've done",
        "This is wonderful news",
        "I'm so grateful for this opportunity",
        "I love spending time with my friends",
        "I'm happy with how things are going",
        "This is exactly what I needed",
        "I'm excited about the future",
        "Thank you for being so supportive",
        "I feel blessed to have this",
        "I'm pleased with the progress",
        "This made my day better",
        "I appreciate your kindness",
        "I'm thankful for this experience",
        "I love this so much",
        "I'm feeling optimistic",
        "Thank you for understanding",
        "I'm grateful for your patience",
        "This is amazing",
        "I feel so much better now",
        "I appreciate the encouragement",
        "I'm happy to be here",
        "Thank you for listening",
        "I'm proud of what I accomplished",
        "I love the way this turned out",
        "I'm thankful for good health",
        "This really helped me",
        "I appreciate your support",
        "I'm feeling hopeful",
        "Thank you for caring",
        "I'm grateful for this opportunity",
        "I love my life right now",
        "I'm happy with the results",
        "Thank you for everything",
        "I appreciate your time",
        "I'm feeling positive today",
        "This is excellent",
        "I'm grateful for my family",
        "Thank you for the advice",
        "I love learning new things",
        "I'm happy to help",
        "I appreciate the opportunity",
        "I'm feeling content",
        "Thank you for your generosity",
        "I'm grateful for the support",
        "I love this community",
        "I'm happy about the news",
        "Thank you for the encouragement",
        "I appreciate your friendship",
        "I'm feeling inspired",
        "This is really helpful",
        "I'm grateful for the chance",
        "Thank you for believing in me",
        "I love the positive energy",
        "I'm happy with my progress",
        "I appreciate the guidance",
        "I'm feeling motivated",
        "Thank you for your compassion",
        "I'm grateful every day",
    ]
    
    for text in positive_examples:
        training_data.append({
            'text': text,
            'labels': {'neutral': 0, 'stress': 0, 'unsafe_environment': 0, 
                      'emotional_distress': 0, 'self_harm_low': 0, 'self_harm_high': 0}
        })
    
    # Shuffle the data
    random.shuffle(training_data)
    
    # Save to file
    with open('training_data.json', 'w', encoding='utf-8') as f:
        json.dump(training_data, f, indent=2, ensure_ascii=False)
    
    print(f"Generated {len(training_data)} training examples")
    print(f"Neutral: {len(neutral_examples)}")
    print(f"Stress: {len(stress_examples)}")
    print(f"Unsafe Environment: {len(unsafe_examples)}")
    print(f"Emotional Distress: {len(emotional_distress_examples)}")
    print(f"Self Harm Low: {len(self_harm_low_examples)}")
    print(f"Self Harm High: {len(self_harm_high_examples)}")
    print(f"Positive: {len(positive_examples)}")
    print(f"\nTotal: {len(training_data)} examples")
    print(f"Saved to training_data.json")

if __name__ == '__main__':
    generate_training_data()
